// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RoomStatus.
const (
	Playing RoomStatus = "playing"
	Waiting RoomStatus = "waiting"
)

// Valid indicates whether the value is a known member of the RoomStatus enum.
func (e RoomStatus) Valid() bool {
	switch e {
	case Playing:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for RoomCreatedEventEventType.
const (
	RoomCreated RoomCreatedEventEventType = "room_created"
)

// Valid indicates whether the value is a known member of the RoomCreatedEventEventType enum.
func (e RoomCreatedEventEventType) Valid() bool {
	switch e {
	case RoomCreated:
		return true
	default:
		return false
	}
}

// Defines values for RoomDeletedEventEventType.
const (
	RoomDeleted RoomDeletedEventEventType = "room_deleted"
)

// Valid indicates whether the value is a known member of the RoomDeletedEventEventType enum.
func (e RoomDeletedEventEventType) Valid() bool {
	switch e {
	case RoomDeleted:
		return true
	default:
		return false
	}
}

// Defines values for RoomUpdatedEventEventType.
const (
	RoomUpdated RoomUpdatedEventEventType = "room_updated"
)

// Valid indicates whether the value is a known member of the RoomUpdatedEventEventType enum.
func (e RoomUpdatedEventEventType) Valid() bool {
	switch e {
	case RoomUpdated:
		return true
	default:
		return false
	}
}

// AnswerSubmitEvent defines model for AnswerSubmitEvent.
type AnswerSubmitEvent struct {
	Answer string `json:"answer"`
}

// ClientDisconnectedEvent defines model for ClientDisconnectedEvent.
type ClientDisconnectedEvent struct {
	// NewDrawerId 現在のdrawerが切断した場合、新しいdrawerのIDが含まれる。切断したのが最後の1人で、次のdrawerに指定できる人がいない場合は含まれない
	NewDrawerId *string `json:"newDrawerId,omitempty"`

	// UserId 切断したユーザーのtraQ ID
	UserId string `json:"userId"`
}

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	Name string `json:"name"`
}

// DrawStrokeEvent defines model for DrawStrokeEvent.
type DrawStrokeEvent struct {
	X1 float64 `json:"x1"`
	X2 float64 `json:"x2"`
	Y1 float64 `json:"y1"`
	Y2 float64 `json:"y2"`
}

// GameEndEvent defines model for GameEndEvent.
type GameEndEvent struct {
	// Cleared クリアしたかどうか
	Cleared bool `json:"cleared"`

	// RemainingLives 残っている残機の数
	RemainingLives int     `json:"remainingLives"`
	Rounds         []Round `json:"rounds"`

	// TotalTimeMs かかった時間（ミリ秒）
	TotalTimeMs int `json:"totalTimeMs"`
}

// Room defines model for Room.
type Room struct {
	Id      openapi_types.UUID `json:"id"`
	Members []RoomMember       `json:"members"`
	Name    string             `json:"name"`
	Status  RoomStatus         `json:"status"`
}

// RoomStatus defines model for Room.Status.
type RoomStatus string

// RoomCreatedEvent defines model for RoomCreatedEvent.
type RoomCreatedEvent struct {
	EventType RoomCreatedEventEventType `json:"eventType"`
	Room      Room                      `json:"room"`
}

// RoomCreatedEventEventType defines model for RoomCreatedEvent.EventType.
type RoomCreatedEventEventType string

// RoomDeletedEvent defines model for RoomDeletedEvent.
type RoomDeletedEvent struct {
	EventType RoomDeletedEventEventType `json:"eventType"`
	RoomId    openapi_types.UUID        `json:"roomId"`
}

// RoomDeletedEventEventType defines model for RoomDeletedEvent.EventType.
type RoomDeletedEventEventType string

// RoomJoinEvent defines model for RoomJoinEvent.
type RoomJoinEvent struct {
	RoomId openapi_types.UUID `json:"roomId"`
}

// RoomListUpdatedEvent defines model for RoomListUpdatedEvent.
type RoomListUpdatedEvent struct {
	union json.RawMessage
}

// RoomMember defines model for RoomMember.
type RoomMember struct {
	// Id traQ ID
	Id      string `json:"id"`
	IsReady bool   `json:"isReady"`
}

// RoomUpdatedEvent defines model for RoomUpdatedEvent.
type RoomUpdatedEvent struct {
	EventType RoomUpdatedEventEventType `json:"eventType"`
	Room      Room                      `json:"room"`
}

// RoomUpdatedEventEventType defines model for RoomUpdatedEvent.EventType.
type RoomUpdatedEventEventType string

// Round defines model for Round.
type Round struct {
	ActualAnswer  string             `json:"actualAnswer"`
	GuesserAnswer string             `json:"guesserAnswer"`
	GuesserId     string             `json:"guesserId"`
	Id            openapi_types.UUID `json:"id"`
	Strokes       []Stroke           `json:"strokes"`

	// TimeMs このラウンドにかかった時間（ミリ秒）
	TimeMs int `json:"timeMs"`
}

// RoundAnswerEvent defines model for RoundAnswerEvent.
type RoundAnswerEvent struct {
	// ActualAnswer 正しい答え
	ActualAnswer string `json:"actualAnswer"`

	// GuesserAnswer Guesserの回答
	GuesserAnswer string `json:"guesserAnswer"`
}

// RoundStartedEvent defines model for RoundStartedEvent.
type RoundStartedEvent struct {
	// GuesserId GuesserのtraQ ID
	GuesserId string `json:"guesserId"`

	// Kanji そのラウンドの漢字（Guesserには送られない）
	Kanji *string `json:"kanji,omitempty"`

	// RoundIndex 何文字目か（1-indexed）
	RoundIndex int `json:"roundIndex"`
}

// Stroke defines model for Stroke.
type Stroke struct {
	DrawerId string  `json:"drawerId"`
	X1       float64 `json:"x1"`
	X2       float64 `json:"x2"`
	Y1       float64 `json:"y1"`
	Y2       float64 `json:"y2"`
}

// TurnStartedEvent defines model for TurnStartedEvent.
type TurnStartedEvent struct {
	// DrawerId そのターンに線を引くdrawerのtraQ ID
	DrawerId string `json:"drawerId"`

	// TurnIndex 何画目か（1-indexed）
	TurnIndex int `json:"turnIndex"`
}

// User defines model for User.
type User struct {
	// Id traQ ID
	Id string `json:"id"`
}

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = CreateRoomRequest

// AsRoomCreatedEvent returns the union data inside the RoomListUpdatedEvent as a RoomCreatedEvent
func (t RoomListUpdatedEvent) AsRoomCreatedEvent() (RoomCreatedEvent, error) {
	var body RoomCreatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRoomCreatedEvent overwrites any union data inside the RoomListUpdatedEvent as the provided RoomCreatedEvent
func (t *RoomListUpdatedEvent) FromRoomCreatedEvent(v RoomCreatedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRoomCreatedEvent performs a merge with any union data inside the RoomListUpdatedEvent, using the provided RoomCreatedEvent
func (t *RoomListUpdatedEvent) MergeRoomCreatedEvent(v RoomCreatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRoomUpdatedEvent returns the union data inside the RoomListUpdatedEvent as a RoomUpdatedEvent
func (t RoomListUpdatedEvent) AsRoomUpdatedEvent() (RoomUpdatedEvent, error) {
	var body RoomUpdatedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRoomUpdatedEvent overwrites any union data inside the RoomListUpdatedEvent as the provided RoomUpdatedEvent
func (t *RoomListUpdatedEvent) FromRoomUpdatedEvent(v RoomUpdatedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRoomUpdatedEvent performs a merge with any union data inside the RoomListUpdatedEvent, using the provided RoomUpdatedEvent
func (t *RoomListUpdatedEvent) MergeRoomUpdatedEvent(v RoomUpdatedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRoomDeletedEvent returns the union data inside the RoomListUpdatedEvent as a RoomDeletedEvent
func (t RoomListUpdatedEvent) AsRoomDeletedEvent() (RoomDeletedEvent, error) {
	var body RoomDeletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRoomDeletedEvent overwrites any union data inside the RoomListUpdatedEvent as the provided RoomDeletedEvent
func (t *RoomListUpdatedEvent) FromRoomDeletedEvent(v RoomDeletedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRoomDeletedEvent performs a merge with any union data inside the RoomListUpdatedEvent, using the provided RoomDeletedEvent
func (t *RoomListUpdatedEvent) MergeRoomDeletedEvent(v RoomDeletedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RoomListUpdatedEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RoomListUpdatedEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/me)
	GetMe(ctx *echo.Context) error

	// (GET /api/rooms)
	GetRooms(ctx *echo.Context) error

	// (POST /api/rooms)
	CreateRoom(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// GetRooms converts echo context to params.
func (w *ServerInterfaceWrapper) GetRooms(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRooms(ctx)
	return err
}

// CreateRoom converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRoom(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRoom(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.GET(options.BaseURL+"/api/rooms", wrapper.GetRooms, options.OperationMiddlewares["getRooms"]...)
	router.POST(options.BaseURL+"/api/rooms", wrapper.CreateRoom, options.OperationMiddlewares["createRoom"]...)

}
